# 最小自動接続間隔を 7.5 ミリ秒に設定します。
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6

# 11.25msのサブハンドがメインハンドにリンクする時間間隔
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9

# レイテンシが0の場合、セカンダリデバイスは接続イベントをスキップせず、常にアクティブリスニング状態を維持します。これにより、プライマリデバイスがディープスリープ状態にあるために起動できないという問題は解決されますが、セカンダリデバイスの消費電力はわずかに増加します。
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

#4000ミリ秒を超える場合、この時間内に通信がない場合に限り、接続が切断されます。
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

#ノブを回す
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# MOUSE
CONFIG_ZMK_POINTING=y

# CONFIG_ZMK_EXT_POWER=y

# キーボードのデバウンスを追加する
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# キーボードのRGB機能を有効にする
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_LED_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
#このファイルは両側に適用される分割形式です。内部の左右confファイルは、両側で異なる機能設定を行う場合に使用します。

# Bluetooth強化
# CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# キー変更
CONFIG_ZMK_STUDIO=y

CONFIG_ZMK_POINTING_MOVEMENT_SENSITIVITY_0=600
CONFIG_ZMK_POINTING_MOVEMENT_SENSITIVITY_1=1000
CONFIG_ZMK_POINTING_MOVEMENT_SENSITIVITY_2=1600
＃DPIスイッチ

CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y



